package sim

// Back-compat proofs (spec 086 T018/T019, US3, FR-004, SC-003): the
// checked-in pre-086 fixture (generated by PRE-086 code at the branch's
// merge-base — bare-int payloads across executor drives and injected rows)
// replays from genesis under THIS build to byte-identical state; the
// pre-086 state snapshot decodes and re-marshals byte-identically and its
// stored-bytes hash verifies; world.migrated's embedded State is untouched;
// mixed-era continuation and same-seed double-run byte-equality hold.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/evanstern/promptworld/internal/store"
)

func loadPre086Events(t *testing.T) []store.Event {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "pre086", "pre086_events.json"))
	if err != nil {
		t.Fatal(err)
	}
	var evs []store.Event
	if err := json.Unmarshal(b, &evs); err != nil {
		t.Fatal(err)
	}
	if len(evs) == 0 {
		t.Fatal("empty fixture")
	}
	// The fixture is byte-frozen pre-086 history and so speaks log format 1
	// (metatron.*). Under spec 094 a real log of this era is TRANSLATED
	// before this build ever replays it, so the loader applies exactly the
	// migration's type mapping — payloads untouched — before the fold; the
	// dual-shape AgentRef proofs this file exists for are payload-level and
	// unaffected.
	for i := range evs {
		evs[i].Type = CanonicalEventType(evs[i].Type)
	}
	return evs
}

func loadPre086State(t *testing.T) ([]byte, string) {
	t.Helper()
	sb, err := os.ReadFile(filepath.Join("testdata", "pre086", "pre086_state.json"))
	if err != nil {
		t.Fatal(err)
	}
	hb, err := os.ReadFile(filepath.Join("testdata", "pre086", "pre086_hash.txt"))
	if err != nil {
		t.Fatal(err)
	}
	return sb, string(hb)
}

// TestPre086ReplayByteIdentity (US3 AS-1): from-genesis replay of the
// pre-086 log under this build produces byte-identical State.Marshal() and
// Hash() to what pre-086 code recorded — no state shape, fold, or hash
// change anywhere. This is the AC #4 keystone.
func TestPre086ReplayByteIdentity(t *testing.T) {
	const seed = 42
	m := testMap(seed)
	s := NewState(seed, m)
	evs := loadPre086Events(t)
	for _, e := range evs {
		if err := s.Apply(e); err != nil {
			t.Fatalf("replaying pre-086 %s at tick %d: %v", e.Type, e.Tick, err)
		}
		if e.Tick > s.Tick {
			s.Tick = e.Tick
		}
	}
	wantState, wantHash := loadPre086State(t)
	if got := s.Marshal(); !bytes.Equal(got, wantState) {
		t.Fatalf("replayed state bytes diverged from pre-086 bytes (len %d vs %d)", len(got), len(wantState))
	}
	if got := s.Hash(); got != wantHash {
		t.Fatalf("replayed hash = %s, want %s", got, wantHash)
	}
}

// TestPre086SnapshotDecodes (US3 AS-2): a pre-086 snapshot's state bytes
// decode into today's State and re-marshal byte-identically (state shapes
// unchanged), and the snapshot hash — SHA-256 over the STORED bytes, the
// store.SaveSnapshot contract — still verifies.
func TestPre086SnapshotDecodes(t *testing.T) {
	stored, wantHash := loadPre086State(t)
	sum := sha256.Sum256(stored)
	if got := hex.EncodeToString(sum[:]); got != wantHash {
		t.Fatalf("stored-bytes hash = %s, want %s (the snapshot verification contract)", got, wantHash)
	}
	var s State
	if err := json.Unmarshal(stored, &s); err != nil {
		t.Fatalf("pre-086 snapshot no longer decodes: %v", err)
	}
	if got := s.Marshal(); !bytes.Equal(got, stored) {
		t.Fatal("pre-086 snapshot does not re-marshal byte-identically — a state shape changed")
	}
}

// TestPre086WorldMigratedUntouched (US3 AS-3): the world.migrated payload
// (which embeds the full canonical State) decodes under this build, applies
// through the reducer, and the embedded state re-marshals byte-identically
// — migration never rewrites payloads, and migrated v1–v4 worlds carry no
// agent-named rows until they emit new events.
func TestPre086WorldMigratedUntouched(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "pre086", "pre086_world_migrated.json"))
	if err != nil {
		t.Fatal(err)
	}
	var p WorldMigratedPayload
	if err := json.Unmarshal(raw, &p); err != nil {
		t.Fatalf("world.migrated payload no longer decodes: %v", err)
	}
	wantState, wantHash := loadPre086State(t)
	if got := p.State.Marshal(); !bytes.Equal(got, wantState) {
		t.Fatal("embedded State does not re-marshal byte-identically")
	}
	if got := p.State.Hash(); got != wantHash {
		t.Fatalf("embedded state hash = %s, want %s", got, wantHash)
	}
	// And the payload itself re-marshals byte-identically (shape untouched).
	re := mustPayload(p)
	if !bytes.Equal(re, raw) {
		t.Fatal("world.migrated payload does not round-trip byte-identically")
	}
}

// TestMixedEraContinuation (US3 AS-4, T019): a pre-086 world continued
// under this build — old rows keep their bytes (never re-marshaled), new
// emissions carry names from the next event on. A mixed log is the
// documented, permanent normal (data-model §6).
func TestMixedEraContinuation(t *testing.T) {
	const seed = 42
	m := testMap(seed)
	s := NewState(seed, m)
	old := loadPre086Events(t)
	for _, e := range old {
		if err := s.Apply(e); err != nil {
			t.Fatal(err)
		}
		if e.Tick > s.Tick {
			s.Tick = e.Tick
		}
	}
	// Continue live: the next stretch of sim time emits named rows.
	fresh := driveTicks(t, s, m, s.Tick+1800, nil)
	seen := assertNamedFromBytes(t, fresh)
	if len(seen) == 0 {
		t.Fatal("continuation emitted nothing")
	}
	// Old rows in the mixed feed remain legacy-shaped (their bytes are
	// immutable history); spot-check one agent-bearing legacy row.
	var legacy bool
	for _, e := range old {
		if e.Type == "agent.memory_added" && strings.Contains(string(e.Payload), `"agent":2`) {
			legacy = true
			break
		}
	}
	if !legacy {
		t.Fatal("fixture lost its legacy-shape rows")
	}
}

// TestLegacyShapesThroughEveryMigratedArm (US3 AS-5, T019): legacy-shape
// rows fold through migrated arms identically and are NEVER rejected for a
// missing name — replaying the whole pre-086 fixture (which exercises the
// executor families and the injected arms) twice produces identical bytes.
func TestLegacyShapesThroughEveryMigratedArm(t *testing.T) {
	const seed = 42
	m := testMap(seed)
	evs := loadPre086Events(t)
	run := func() []byte {
		s := NewState(seed, m)
		for _, e := range evs {
			if err := s.Apply(e); err != nil {
				t.Fatalf("arm rejected a legacy row: %s: %v", e.Type, err)
			}
			if e.Tick > s.Tick {
				s.Tick = e.Tick
			}
		}
		return s.Marshal()
	}
	if !bytes.Equal(run(), run()) {
		t.Fatal("legacy replay is not deterministic")
	}
}

// TestSameSeedDoubleRunByteEquality (T019, FR-012): two same-seed drives of
// the post-086 build emit byte-identical event histories — named payloads
// on both sides, the byte-comparable doctrine within a build, and no
// emission-order change.
func TestSameSeedDoubleRunByteEquality(t *testing.T) {
	drive := func() []store.Event {
		const seed = 99
		m := testMap(seed)
		s := NewState(seed, m)
		return driveTicks(t, s, m, 2*3600, nil)
	}
	a, b := drive(), drive()
	if len(a) != len(b) {
		t.Fatalf("event counts diverged: %d vs %d", len(a), len(b))
	}
	for i := range a {
		if a[i].Type != b[i].Type || !bytes.Equal(a[i].Payload, b[i].Payload) || a[i].Tick != b[i].Tick {
			t.Fatalf("event %d diverged: %s %s vs %s %s", i, a[i].Type, a[i].Payload, b[i].Type, b[i].Payload)
		}
	}
}
