package tool

// Explain fact sheets (spec 063 US1, research R1): the read-only `explain`
// tool's deterministic answer path. Every sheet is composed HERE, tool-side,
// from the same registry entries and doctrine constants the mechanics run on
// — "described ≡ declared by construction", extended from the prompt surface
// (derive.go) to the player-facing answer path. The model chooses WHEN to
// call and how to converse around the answer; it can never alter the fact
// text itself (spec 063 standing resolution 3): zero model-generated bytes
// in any sheet (SC-001).
//
// This package is a leaf (spec 014 research R1), so doctrine that lives in
// other packages is MIRRORED here with a drift-pin test in the owning
// package — the established miracleKinds/clockSpeeds/PlanStepCap pattern:
//   - the charge economy (cap/genesis/regen) mirrors internal/sim's
//     GuardianChargeCap/GuardianGenesisCharges/GuardianChargeRegenTicks
//     (pinned by sim's TestExplainChargeDoctrineMirrorsSim);
//   - the decision-class vocabulary mirrors internal/toolloop's Verdict
//     constants (pinned by toolloop's TestExplainDecisionClassesMirrorVerdicts);
//   - the map-glyph legend mirrors internal/tui's mapGlyphs table (pinned by
//     tui's TestExplainGlyphsMirrorLegend).

import (
	"fmt"
	"sort"
	"strings"
)

// ExplainScope is the world slice a fact sheet describes (spec 063 FR-001):
// the sheet reflects the world's EFFECTIVE grant and stage ceiling — the
// roster facts describe THIS world, not the full catalog — while cataloged-
// but-ungranted tools are named as existing-but-ungranted (edge case: the
// sheet never pretends a tool doesn't exist, and never teaches a verb the
// world lacks without saying so).
type ExplainScope struct {
	// Granted is the world's effective granted roster in turn order — the
	// SAME slice that feeds the loop declaration, the derived guidance, and
	// the handler set (guardian grantedRoster + granted bundle tools), so
	// the sheet can never disagree with what the turn actually offers.
	// work_miracle arrives with its kind enum already narrowed (RestrictEnum).
	Granted []Tool
	// Catalog is the full declared guardian catalog (LoopRosterGuardian),
	// grant-independent — the honest-catalog half of the grant distinction.
	Catalog []Tool
	// Stage is the world's neutral curriculum stage id ("" = pre-ladder).
	Stage string
}

// explainTopics is the fixed topic vocabulary, in catalog order (data-model
// v1): per-topic sheets plus `<tool-id>` detail for any cataloged tool.
var explainTopics = []string{"roster", "costs", "charges", "workings", "decisions", "glyphs"}

// ExplainTopics returns a copy of the fixed topic vocabulary, in catalog
// order (the `<tool-id>` detail topics come from the live catalog and are
// not listed here).
func ExplainTopics() []string {
	out := make([]string, len(explainTopics))
	copy(out, explainTopics)
	return out
}

// The charge-economy doctrine constants, MIRRORED from internal/sim (leaf
// discipline; sim's TestExplainChargeDoctrineMirrorsSim pins all three).
const (
	explainChargeCap      = 3 // sim.GuardianChargeCap
	explainGenesisCharges = 1 // sim.GuardianGenesisCharges
	explainRegenGameHours = 6 // sim.GuardianChargeRegenTicks / 3600
)

// ChargeDoctrine exposes the mirrored charge-economy constants (cap, genesis
// grant, regeneration cadence in game hours) for the sim-side drift pin.
func ChargeDoctrine() (cap, genesis, regenGameHours int) {
	return explainChargeCap, explainGenesisCharges, explainRegenGameHours
}

// decisionClasses is the recorded verdict vocabulary (TASK-63 / spec 017
// data-model §5) with a player-facing meaning per class — MIRRORED from
// internal/toolloop's Verdict constants (toolloop's drift pin holds the name
// set equal). Order is the record.go declaration order.
var decisionClasses = []struct{ Name, Meaning string }{
	{"landed", "an act was admitted by its door and its events grounded — the turn's one act"},
	{"landed_clamped", "landed, after an over-long text field was trimmed to its cap first"},
	{"rejected_gate", "the door refused (no charge banked, bad target, night-only, not granted here) — nothing was spent; the ask can be repaired"},
	{"rejected_cardinality", "a second act arrived after one had already landed — one act per turn"},
	{"rejected_unknown", "the call named a tool this world does not offer"},
	{"rejected_malformed", "the arguments did not fit the tool's declared shape"},
	{"read_ok", "a read returned its data — free, never the act"},
	{"read_error", "a read failed — free, nothing changed"},
	{"unlanded", "the turn ended before the call could ground"},
}

// DecisionClassNames returns the mirrored verdict names in declaration order
// — the toolloop-side drift pin's enumeration surface.
func DecisionClassNames() []string {
	out := make([]string, len(decisionClasses))
	for i, d := range decisionClasses {
		out[i] = d.Name
	}
	return out
}

// explainGlyph is one row of the mirrored map legend.
type explainGlyph struct {
	Glyph   string
	Name    string
	Meaning string
}

// explainGlyphs MIRRORS internal/tui's mapGlyphs table (help.go) — the one
// legend source renderMapGrid and the help overlay already share; tui's
// TestExplainGlyphsMirrorLegend pins this copy equal so the explained legend
// can never drift from the drawn one.
var explainGlyphs = []explainGlyph{
	{"~", "water", "water — impassable to foot travel"},
	{"♠", "wood", "a tree — choppable for wood"},
	{"\"", "forage", "wild forage — gatherable food"},
	{"^", "rock", "an intact rock outcrop — quarriable for stone"},
	{",", "quarried", "a depleted outcrop — passable, already quarried"},
	{"ᴥ", "den", "a gru's den"},
	{"▲", "fire", "a lit fire — warmth, cooking"},
	{"△", "cold", "a cold fire, out of fuel"},
	{"⌂", "shelter", "a built shelter"},
	{"▣", "oven", "a built oven"},
	{"%", "pile", "a ground stockpile of dropped goods"},
	{"☐", "chest", "a built chest, holding goods"},
	{"▤▩", "wall", "a built wall (▤ plank, ▩ stone); dim = damaged"},
	{"·", "path", "a paved path (tan) — distinct from plain ground's dim ·"},
	{"G", "gru", "the gru — a predator; approach at your peril"},
	{"✝", "grave", "a villager's grave — marks where a death occurred"},
	{"░", "marsh", "marshy wet ground near water — open, walkable"},
	{"▒", "sand", "a sandy shoreline flat — open, walkable"},
	{"S", "stranger", "a stranger — a night trickster after unattended stores"},
	// Guardian designations (spec 084): the plan layer's three marks.
	{"◇", "site", "a guardian-marked structure site — a designation awaiting its building"},
	{"┄", "wallplan", "a guardian-marked wall line — a designation awaiting its wall"},
	{"◦", "zone", "the edge of a guardian-marked settlement zone"},
}

// explainAgentGlyphNote mirrors help.go's agentGlyphNote (same pin test).
const explainAgentGlyphNote = "agents by initial (lowercase asleep, †dead)"

// MapGlyphLegend returns the mirrored legend as (glyph, name, meaning) rows
// plus the trailing agent note — tui's drift pin compares it against the
// rendering table.
func MapGlyphLegend() (rows [][3]string, agentNote string) {
	rows = make([][3]string, len(explainGlyphs))
	for i, g := range explainGlyphs {
		rows[i] = [3]string{g.Glyph, g.Name, g.Meaning}
	}
	return rows, explainAgentGlyphNote
}

// ExplainSheet composes the deterministic fact sheet for topic under scope.
// Topic matching is case-insensitive and trims space; an empty or unknown
// topic returns the explainable-topic catalog (the honest, repairable miss —
// never a fabricated answer). The result is byte-stable for identical
// (registry, scope, topic) inputs: every list walks a declared slice, never
// a Go map.
func ExplainSheet(topic string, sc ExplainScope) string {
	t := strings.ToLower(strings.TrimSpace(topic))
	switch t {
	case "roster":
		return explainRoster(sc)
	case "costs":
		return explainCosts(sc)
	case "charges":
		return explainCharges()
	case "workings":
		return explainWorkings(sc)
	case "decisions":
		return explainDecisions()
	case "glyphs":
		return explainGlyphsSheet()
	}
	if tl, granted, ok := scopeLookup(sc, t); ok {
		return explainToolDetail(tl, granted, sc)
	}
	if t == "" {
		return explainCatalog(sc)
	}
	return fmt.Sprintf("%q is not a topic I can explain.\n\n%s", topic, explainCatalog(sc))
}

// scopeLookup resolves a tool-id topic against the granted roster first (a
// granted bundle tool is explainable even though the static catalog doesn't
// know it), then the full catalog (the existing-but-ungranted case).
func scopeLookup(sc ExplainScope, name string) (tl Tool, granted, ok bool) {
	for _, t := range sc.Granted {
		if t.Name == name {
			return t, true, true
		}
	}
	for _, t := range sc.Catalog {
		if t.Name == name {
			return t, false, true
		}
	}
	return Tool{}, false, false
}

// grantedNames returns the granted roster's names in roster order.
func grantedNames(sc ExplainScope) []string {
	out := make([]string, len(sc.Granted))
	for i, t := range sc.Granted {
		out[i] = t.Name
	}
	return out
}

// ungrantedNames returns cataloged tools absent from the granted roster, in
// catalog order.
func ungrantedNames(sc ExplainScope) []string {
	g := make(map[string]bool, len(sc.Granted))
	for _, t := range sc.Granted {
		g[t.Name] = true
	}
	var out []string
	for _, t := range sc.Catalog {
		if !g[t.Name] {
			out = append(out, t.Name)
		}
	}
	return out
}

// explainCatalog is the topic catalog — the miss result and the empty-topic
// result: what CAN be explained, including this scope's tool-id topics.
func explainCatalog(sc ExplainScope) string {
	var b strings.Builder
	b.WriteString("Topics I can explain: ")
	b.WriteString(strings.Join(explainTopics, ", "))
	b.WriteString(".")
	names := append(grantedNames(sc), ungrantedNames(sc)...)
	sort.Strings(names)
	if len(names) > 0 {
		b.WriteString(" I can also explain any single tool by name: ")
		b.WriteString(strings.Join(names, ", "))
		b.WriteString(".")
	}
	return b.String()
}

// toolDescLine renders one roster tool's single descriptive line — the same
// guardianToolDesc gloss the turn guidance uses (PromptGloss fallback for
// bundle tools), so a described tool reads the same in both surfaces.
func toolDescLine(t Tool) string {
	desc, ok := guardianToolDesc[t.Name]
	if !ok {
		desc = t.PromptGloss
	}
	if desc == "" {
		desc = "(no description)"
	}
	return desc
}

// explainRoster describes what THIS world grants, then names what exists in
// the catalog but is not granted here (the grant distinction, edge case 1).
func explainRoster(sc ExplainScope) string {
	var b strings.Builder
	b.WriteString("roster — what this world grants\n")
	if len(sc.Granted) == 0 {
		b.WriteString("- no acting tools are granted in this world; counsel in words is always available\n")
	}
	for _, t := range sc.Granted {
		fmt.Fprintf(&b, "- %s(%s) — %s\n", t.Name, paramNameList(t), toolDescLine(t))
	}
	if un := ungrantedNames(sc); len(un) > 0 {
		fmt.Fprintf(&b, "Cataloged but not granted in this world: %s.\n", strings.Join(un, ", "))
	}
	if sc.Stage != "" {
		fmt.Fprintf(&b, "This world's stage: %s — the stage ceiling caps what any world file may grant.\n", sc.Stage)
	}
	return strings.TrimRight(b.String(), "\n")
}

// explainCosts prices every granted tool from the registry's own cost data —
// Cost.Charges for the flat-priced tools, the authoritative MiracleCost table
// per working kind — so a described price can never drift from the enforced
// one (the GuardianToolGuidance property, extended to the answer path).
func explainCosts(sc ExplainScope) string {
	var b strings.Builder
	b.WriteString("costs — what each tool spends\n")
	for _, t := range sc.Granted {
		if t.Name == "work_miracle" {
			b.WriteString("- work_miracle — per kind:\n")
			for _, k := range enumValues(t, "kind") {
				cost, _ := MiracleCost(k)
				fmt.Fprintf(&b, "    %q — %d %s\n", k, cost, chargeWord(cost))
			}
			continue
		}
		if t.Effect == Read {
			fmt.Fprintf(&b, "- %s — free (a read: no charge, and it never counts as the turn's act)\n", t.Name)
			continue
		}
		c := t.Cost.Charges
		if c == 0 {
			fmt.Fprintf(&b, "- %s — 0 charges (free, but it is the turn's one act)\n", t.Name)
			continue
		}
		fmt.Fprintf(&b, "- %s — %d %s\n", t.Name, c, chargeWord(c))
	}
	b.WriteString("Speaking and refusing are always free.")
	return b.String()
}

// explainCharges renders the charge economy from the mirrored doctrine
// constants (sim-pinned — see the header comment).
func explainCharges() string {
	return fmt.Sprintf(`charges — the acting economy
- the bank holds at most %d charges
- a new world begins with %d charge banked
- one charge regenerates every %d game hours (at absolute clock boundaries), up to the cap
- acting spends charges (see "costs"); speaking, reading, and refusing are free`,
		explainChargeCap, explainGenesisCharges, explainRegenGameHours)
}

// explainWorkings describes the direct world edits: the work_miracle tool's
// kind vocabulary, per-kind arguments (miracleKindArgs), and per-kind price
// (MiracleCost) — scoped to the granted kind enum, with ungranted kinds
// named honestly (edge case 1). "working" is the display vocabulary for the
// frozen work_miracle mechanics family (spec 052 FR-007); the tool id is
// what the model calls.
func explainWorkings(sc ExplainScope) string {
	var b strings.Builder
	b.WriteString("workings — direct world edits (the work_miracle tool)\n")
	wm, granted, ok := scopeLookup(sc, "work_miracle")
	if !ok {
		b.WriteString("- this catalog has no working tool")
		return b.String()
	}
	if !granted {
		b.WriteString("work_miracle exists in the catalog but is NOT granted in this world — asking for a working will be refused.\n")
		wm, _ = Lookup("work_miracle")
	}
	offered := enumValues(wm, "kind")
	for _, k := range offered {
		cost, _ := MiracleCost(k)
		fmt.Fprintf(&b, "- %q with %s — %d %s\n", k, miracleKindArgs[k], cost, chargeWord(cost))
	}
	if granted {
		off := make(map[string]bool, len(offered))
		for _, k := range offered {
			off[k] = true
		}
		var un []string
		for _, k := range miracleKinds {
			if !off[k] {
				un = append(un, k)
			}
		}
		if len(un) > 0 {
			fmt.Fprintf(&b, "Cataloged kinds not granted in this world: %s.\n", strings.Join(un, ", "))
		}
	}
	b.WriteString("A working can never be free, and a villager can never be removed.")
	return b.String()
}

// explainDecisions renders the recorded verdict vocabulary (mirrored,
// toolloop-pinned).
func explainDecisions() string {
	var b strings.Builder
	b.WriteString("decisions — how each tool call is judged and recorded\n")
	for _, d := range decisionClasses {
		fmt.Fprintf(&b, "- %s — %s\n", d.Name, d.Meaning)
	}
	b.WriteString("Every call lands exactly one of these in the world's record.")
	return b.String()
}

// explainGlyphsSheet renders the mirrored map legend (tui-pinned).
func explainGlyphsSheet() string {
	var b strings.Builder
	b.WriteString("glyphs — the map legend\n")
	for _, g := range explainGlyphs {
		fmt.Fprintf(&b, "- %s %s — %s\n", g.Glyph, g.Name, g.Meaning)
	}
	b.WriteString("- " + explainAgentGlyphNote)
	return b.String()
}

// explainToolDetail is the `<tool-id>` sheet: what the tool does, its
// argument surface, its price, and — the grant distinction — whether THIS
// world offers it.
func explainToolDetail(t Tool, granted bool, sc ExplainScope) string {
	var b strings.Builder
	status := "granted in this world"
	if !granted {
		status = "cataloged, but NOT granted in this world — asking for it will be refused"
	}
	fmt.Fprintf(&b, "%s — %s\n", t.Name, status)
	fmt.Fprintf(&b, "- what: %s\n", toolDescLine(t))
	if args := paramNameList(t); args != "" {
		fmt.Fprintf(&b, "- arguments: %s\n", args)
	}
	switch {
	case t.Name == "work_miracle":
		b.WriteString("- cost, per kind:\n")
		for _, k := range enumValues(t, "kind") {
			cost, _ := MiracleCost(k)
			fmt.Fprintf(&b, "    %q with %s — %d %s\n", k, miracleKindArgs[k], cost, chargeWord(cost))
		}
	case t.Effect == Read:
		b.WriteString("- cost: free — a read returns facts, spends nothing, and never counts as the turn's act\n")
	default:
		fmt.Fprintf(&b, "- cost: %d %s; landing it is the turn's one act\n", t.Cost.Charges, chargeWord(t.Cost.Charges))
	}
	return strings.TrimRight(b.String(), "\n")
}
